# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SwarmClef < Formula
  desc "Ethereum Clef"
  homepage "https://swarm.ethereum.org/"
  version "0.11.0-rc1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ethersphere/bee-clef/releases/download/v0.11.0-rc1/bee-clef-darwin-arm64.tar.gz"
      sha256 "c84216c865d0e5b16adbf7545c0ae53abe8fe4ffcddb07bd28ee59eaa9380af9"

      def install
        (etc/"swarm-clef").mkpath
        (var/"lib/swarm-clef").mkpath
        bin.install ["bee-clef", "swarm-clef", "swarm-clef-init", "swarm-clef-keys"]
        etc.install "packaging/default" => "swarm-clef/default" unless File.exists? etc/"swarm-clef/default"
        etc.install "packaging/4byte.json" => "swarm-clef/4byte.json" unless File.exists? etc/"swarm-clef/4byte.json"
        etc.install "packaging/rules.js" => "swarm-clef/rules.js" unless File.exists? etc/"swarm-clef/rules.js"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ethersphere/bee-clef/releases/download/v0.11.0-rc1/bee-clef-darwin-amd64.tar.gz"
      sha256 "94e99008d9b96782477c54de263b7e988f16de1123add39eb459dbcf6eedfe84"

      def install
        (etc/"swarm-clef").mkpath
        (var/"lib/swarm-clef").mkpath
        bin.install ["bee-clef", "swarm-clef", "swarm-clef-init", "swarm-clef-keys"]
        etc.install "packaging/default" => "swarm-clef/default" unless File.exists? etc/"swarm-clef/default"
        etc.install "packaging/4byte.json" => "swarm-clef/4byte.json" unless File.exists? etc/"swarm-clef/4byte.json"
        etc.install "packaging/rules.js" => "swarm-clef/rules.js" unless File.exists? etc/"swarm-clef/rules.js"
      end
    end
  end

  def post_install
    unless File.exists? "#{var}/lib/swarm-clef/password"
system("openssl", "rand", "-out", var/"lib/swarm-clef/password", "-base64", "32")
end
system(bin/"swarm-clef-init", ">/dev/null", "2>&1")

  end

  def caveats; <<~EOS
    Logs: #{var}/log/swarm-clef/swarm-clef.log
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>#{plist_name}</string>
  <key>ProgramArguments</key>
  <array>
    <string>#{bin}/swarm-clef</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>#{var}/log/swarm-clef/swarm-clef.log</string>
  <key>StandardErrorPath</key>
  <string>#{var}/log/swarm-clef/swarm-clef.log</string>
</dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/bee-clef --version"
  end
end
