# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SwarmClef < Formula
  desc "Ethereum Clef"
  homepage "https://swarm.ethereum.org/"
  version "0.10.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ethersphere/bee-clef/releases/download/v0.10.0/bee-clef-darwin-arm64.tar.gz"
      sha256 "7e0959e548af1b11d87b690837c2fc3b6607923535d72791f8309db69aa5fcc6"

      def install
        (etc/"swarm-clef").mkpath
        (var/"lib/swarm-clef").mkpath
        bin.install ["bee-clef", "swarm-clef", "swarm-clef-init", "swarm-clef-keys"]
        etc.install "packaging/default" => "swarm-clef/default" unless File.exists? etc/"swarm-clef/default"
        etc.install "packaging/4byte.json" => "swarm-clef/4byte.json" unless File.exists? etc/"swarm-clef/4byte.json"
        etc.install "packaging/rules.js" => "swarm-clef/rules.js" unless File.exists? etc/"swarm-clef/rules.js"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ethersphere/bee-clef/releases/download/v0.10.0/bee-clef-darwin-amd64.tar.gz"
      sha256 "7ed3c80b138241a5b42fe88e6dfeb614c699b6d52763e729d48745c8d075188f"

      def install
        (etc/"swarm-clef").mkpath
        (var/"lib/swarm-clef").mkpath
        bin.install ["bee-clef", "swarm-clef", "swarm-clef-init", "swarm-clef-keys"]
        etc.install "packaging/default" => "swarm-clef/default" unless File.exists? etc/"swarm-clef/default"
        etc.install "packaging/4byte.json" => "swarm-clef/4byte.json" unless File.exists? etc/"swarm-clef/4byte.json"
        etc.install "packaging/rules.js" => "swarm-clef/rules.js" unless File.exists? etc/"swarm-clef/rules.js"
      end
    end
  end

  def post_install
    unless File.exists? "#{var}/lib/swarm-clef/password"
system("openssl", "rand", "-out", var/"lib/swarm-clef/password", "-base64", "32")
end
system(bin/"swarm-clef-init", ">/dev/null", "2>&1")

  end

  def caveats; <<~EOS
    Logs: #{var}/log/swarm-clef/swarm-clef.log
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>#{plist_name}</string>
  <key>ProgramArguments</key>
  <array>
    <string>#{bin}/swarm-clef</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>#{var}/log/swarm-clef/swarm-clef.log</string>
  <key>StandardErrorPath</key>
  <string>#{var}/log/swarm-clef/swarm-clef.log</string>
</dict>
</plist>

  EOS
  end

  test do
    system "#{bin}/bee-clef --version"
  end
end
